version: "3"

services:
  pg:
    build:
      context: "."
      dockerfile: Dockerfile.lexicon
    environment:
      - POSTGRES_DB=test_data_for_chisel
      - POSTGRES_USER=ryan
      - POSTGRES_PASSWORD=r
      - TRAVIS_BRANCH
      - GITHUB_REF_NAME
    image: postgres:14.2-alpine
    ports:
      - "8765:5432"
  lexicon:
    build:
      context: "."
      dockerfile: Dockerfile.lexicon
    ports:
      - "9876:5432"
  sqlite:
    image: busybox
    command: sleep infinity
  loadmop:
    depends_on:
      - pg
      - lexicon
      - sqlite
    build:
      context: "."
      dockerfile: Dockerfile
    environment:
      - DOCKER_HUB_PASSWORD
      - DOCKER_HUB_USER
      - DROPBOX_OAUTH_BEARER
      - TRAVIS_BRANCH
      - GITHUB_REF_NAME
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
