---
name: Build GDM DBs
on:
  workflow_dispatch:
  push:
jobs:
  Run-Tests:
    runs-on: ubuntu-22.04
    environment: GDM Secrets
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - 
        name: Log into DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build GDM DBs
        run: docker-compose run loadmop bundle exec rake loadmop:gdm:load loadmop:gdm:upload
        env:
          DROPBOX_OAUTH_BEARER: ${{ secrets.DROPBOX_OAUTH_BEARER }}
          DOCKER_HUB_USER: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKER_HUB_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}
