---
name: Build GDM DBs
on: [push]
jobs:
  Run-Tests:
    runs-on: ubuntu-latest
    environment: GDM Secrets
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - 
        name: Log into DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build GDM DBs
        run: docker-compose run loadmop bundle exec rake loadmop:gdm:load loadmop:gdm:upload